### ISSUE TITLE
Trouble running the example

### ISSUE THREAD

**Issue by larry77** [DenchPokepon/fedstatAPIr#3]
Доброе утро,
Я очень заинтересован в этом проекте, но, похоже, он не работает так, как ожидалось.
Пожалуйста, взгляните на пример ниже.
Можете ли вы сказать мне, в чем проблема?
Спасибо!

``` r
library(fedstatAPIr)
data <- fedstat_data_load_with_filters(
  indicator_id = "31074",
  filters = list(
    "Классификатор объектов административно-территориального деления (ОКАТО)" = "Российская Федерация",
    "Виды показателя" = c(
      "К соответствующему периоду предыдущего года",
      "К предыдущему месяцу"
    ),
    "Период" = "Январь",
    "Год" = "2023",
    "Виды товаров и услуг" = "*"
  )
)
#> Downloading EMISS internal identificators for the https://www.fedstat.ru/indicator/31074 ...
#> Request failed [403]. Retrying in 1.3 seconds...
#> Request failed [403]. Retrying in 1.7 seconds...
#> Error in read_html.response(GET_res, encoding = "UTF-8"): Forbidden (HTTP 403).

sessionInfo()
#> R version 4.3.2 (2023-10-31)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Debian GNU/Linux 12 (bookworm)
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.11.0 
#> LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.11.0
#> 
#> locale:
#>  [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
#>  [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
#>  [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       
#> 
#> time zone: Europe/Brussels
#> tzcode source: system (glibc)
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] fedstatAPIr_1.0.3
#> 
#> loaded via a namespace (and not attached):
#>  [1] vctrs_0.6.4       httr_1.4.7        cli_3.6.1         knitr_1.45       
#>  [5] rlang_1.1.2       xfun_0.41         purrr_1.0.2       styler_1.10.2    
#>  [9] data.table_1.14.8 glue_1.6.2        htmltools_0.5.7   rmarkdown_2.25   
#> [13] R.cache_0.16.0    evaluate_0.23     fastmap_1.1.1     yaml_2.3.7       
#> [17] lifecycle_1.0.4   compiler_4.3.2    fs_1.6.3          R.oo_1.26.0      
#> [21] R.utils_2.12.3    digest_0.6.33     R6_2.5.1          reprex_2.0.2     
#> [25] curl_5.1.0        magrittr_2.0.3    R.methodsS3_1.8.2 tools_4.3.2      
#> [29] withr_2.5.2       xml2_1.3.5
```

<sup>Created on 2024-03-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by DenchPokepon** [comment]
Hello!

I guess you are not a Russian native speaker and don't live in the Russian Federation :)

Sadly, the fedstat.ru is not accessible from anywhere in the world. You need to use VPN to access this website :(

I think only Russian VPN will work, it won't work even from Kazakhstan :( (but i dunno for sure)

**Comment by larry77** [comment]
I see and it is a pity. I will close this soon since there is nothing you can do on your side.
Only 2 questions
1) suggestions for a vpn which may work.
2) It seems to me that rosstat is accessible, do you know how any other tool to retrieve info from there (possibly in R or Python)? 

Thanks

**Comment by DenchPokepon** [comment]
1. Since March 1 2024, it is forbidden to advertise VPNs in Russia. Ahaha what a pity. I think you can find all the information you need online.
2. Yeah, their blocking policies are kind of weird. It's just that fedstat.ru is a website for distributing huge datasets, rosstat's site has only small datasets mainly for Russia as a whole without proper API (it's just a bunch of xlsx/xls files for normal people to use, not for computers). They are constantly changing where these files are published and their formats. The algorithm of actions depends on what kind of information you need. It may be in a good maintained collection, e.g. https://rosstat.gov.ru/compendium/document/50802 (Short-Term Economic Indicators of the Russian Federation). Also there is this page, but I don't know anything about automatic data retrieval https://eng.rosstat.gov.ru/sdds.

**Comment by larry77** [comment]
Tough luck for me!
